spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/clouddo?characterEncoding=utf8&useSSL=false&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: root
    password: root
custom:
  token:
    secret:
      key: 12345678901
    expire: 86400
    confirmExpire : 86400
  session:
    timeOut: 3600