spring:
  application:
    name: peace-config-client
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Joker-Di/peace-cloud.git
          search-paths: peace-config/src/main/resources/{application}
          username:
          password:

server:
  port: 6001

