spring:
  application:
    name: peace-zuul

server:
  port: 5000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: peace-ribbon
    api-b:
      path: /api-b/**
      serviceId: peace-feign

