server:
  port: 20100

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

spring:
  application:
    name: peace-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Joker-Di/peace-cloud.git
          search-paths: peace-config/src/main/resources/{application}
          username: Joker-Di
          password: dong2619
